#!/bin/sh

#########################################################################
# tool to send commands to avatarsay
# this file is in the public domain --Andreas K. Foerster
#
# you may use code from this file and put it under any license
# you wish to use
#########################################################################

VERSION=1

help()
{
cat <<EOF
Usage: avtcmd [options] avatarsay-command

The program sends commands to avatarsay (AKFAvatar).

It must be called from avatarsay.

Options:
 -h, --help       show this help
 -v, --version    show version information
 -s, --sync       synchronize the working directory with avatarsay

Note: 
  This is meant for interactive use only. If you write your own 
  shell-scripts or programs, it is much better to use the 
  escape-sequences directly.

Examples:
 avtcmd size 4, 40             sets the size to 4 lines, 40 rows.
 avtcmd size                   sets the maximum size again
 avtcmd -s avatarimage me.png  changes the avatar-image
 avtcmd -s audio sound1.wav    plays an audio file from the current directory
 avtcmd stopaudio              stops the audio output

Report bugs to <bug-akfavatar@akfoerster.de>
EOF

exit 0
}

version()
{
  echo "avtcmd version: $VERSION"
  if [ -n "$AKFAVTTERM" ]
  then
    echo "AKFAvatar version: $AKFAVTTERM"
  fi
  
  exit 0
}

avatar_command()
{
  if [ -n "$AKFAVTTERM" ]
  then
    printf "\033_%s\033\\" "$*"
  else
    echo "error: must be called from avatarsay" >&2
    exit 1
  fi
}

case "$1" in
  -h | --help | "") help ;;
  -v | --version) version ;;
  -s | --sync) avatar_command datadir `pwd`; shift ;;
esac

[ $# -ge 1 ] && avatar_command "$*"

exit 0

