#!/bin/sh

# This file is in the Public Domain - AKFoerster

# use avatar as reader for manpages
# probably needs the GNU variant of troff: groff

# You can set the Avatar-Image with the environment variable
# AVATARIMAGE

# you may comment out the following line, if you want slowprint mode
OPT_PAGER="--pager"

# check if ./avatarsay-s exists and is executable
if [ -x "./avatarsay" ]
then
  AVATARSAY="$(pwd)/avatarsay"
else
  AVATARSAY="avatarsay"
fi

# split options for man and for avatarsay
AVATAROPTS=""
MANOPTS=""
while [ $# -ne 0 ]
do
  case $1 in
  -w | --window | \
  -f | --fullscreen)	AVATAROPTS="$AVATAROPTS $1" ;;
  *)			MANOPTS="$MANOPTS $1" ;;
  esac
  shift
done

MANWIDTH=80
GROFF_TYPESETTER=latin1
export MANWIDTH GROFF_TYPESETTER

# execute the command
exec man -t $MANOPTS 2>&1 | $AVATARSAY $AVATAROPTS $OPT_PAGER -rl -
