#!/bin/sh

#########################################################################
# GNOME frontend for avatarsay using zenity, gedit and info
# Copyright (c) 2007,2009 Andreas K. Foerster <info@akfoerster.de>
#
# This file is part of AKFAvatar
#
# AKFAvatar is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AKFAvatar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#########################################################################

CONFIGFILE=~/.gnome-akfavatar

# default mode
MODE=--window

# comment that out if you don't want to have the window centered
SDL_VIDEO_CENTERED=1
export SDL_VIDEO_CENTERED

# may be overridden by language specific content
WWW="http://akfavatar.nongnu.org/"

case "$LANG" in
  de*) WWW="http://akfavatar.nongnu.org/akfavatar.de.html"
       INFO="akfavatar-de"
       WHICHTEXT="Welchen Text mit AKFAvatar anzeigen?"
       FILEEDIT="Weche Datei editieren"
       WHICHMANPAGE="Welche Hilfeseite (Manpage) mit AKFAvatar anzeigen?"
       WHICHAVATARIMAGE="Welches Bild als Avatar verwenden?"
       WHICHAVATARIMAGE="$WHICHAVATARIMAGE (\"Abbruch\" für Vorgabe)"
       DEFAULTAVATARIMAGE="Verwende das Vorgabe-Bild als Avatar"
       FULLSCREENMODE="Das Programm im Vollbild-Modus laufen lassen?"
       NOX="muss vom X-Window-System aus gestartet werden"
       NOZENITY="Befehl \"zenity\" nicht gefunden"
       NOAVATARSAY="Befehl \"avatarsay\" nicht gefunden"
       KEY="Taste"
       WHATTODO="was machen"
       RUNTERMINAL="als Terminal verwenden"
       SHOWDEMO="ein Demo oder eine Text-Datei anzeigen"
       EDITDEMO="ein Demo erstellen oder bearbeiten"
       SHOWMANPAGE="eine Hilfeseite (Manpage) anzeigen"
       CHANGEAVATARIMAGE="ändere das Avatar-Bild"
       FULLSCREENORWINDOW="Vollbild- oder Fenster-Modus"
       SAVESETTINGS="speichere Einstellungen"
       HELP="Hilfe für AKFAvatar"
       WEBSITE="Website"
       EXIT="beenden";;

  *)   WWW="http://akfavatar.nongnu.org/akfavatar.en.html"
       INFO="akfavatar-en"
       WHICHTEXT="Which text to show with AKFAvatar?"
       FILEEDIT="file to edit"
       WHICHMANPAGE="Which manpage to show with AKFAvatar?"
       WHICHAVATARIMAGE="Which image to use as avatar? (cancel for default)"
       DEFAULTAVATARIMAGE="Using the default avatar image"
       FULLSCREENMODE="Run the program in fullscreen mode?"
       NOX="must be started from the X-Window-System"
       NOZENITY="Command \"zenity\" not found"
       NOAVATARSAY="Command \"avatarsay\" not found"
       KEY="key"
       WHATTODO="what to do"
       RUNTERMINAL="run as terminal"
       SHOWDEMO="show a demo or textfile"
       EDITDEMO="create or edit a demo"
       SHOWMANPAGE="show a manpage"
       CHANGEAVATARIMAGE="change avatar image"
       FULLSCREENORWINDOW="fullscreen or window mode"
       SAVESETTINGS="save settings"
       HELP="help for AKFAvatar"
       WEBSITE="Website"
       EXIT="Exit";;
esac

#########################################################################
# functions

run_avatarsay ()
{
  local MESSAGE

  if [ "$1" = "-" -o "$1" = "--terminal" -o -r "$1" ]
  then
    if MESSAGE=`$AVATARSAY $MODE "$1" 2>&1`
    then
      [ -n "$MESSAGE" ] && $ZENITY --warning --text="$MESSAGE"
    else
      $ZENITY --error --text="$MESSAGE"
    fi
  fi
}

show_help ()
{
  local MESSAGE

  if MESSAGE=`$AVATARSAY $MODE --info --execute info $INFO 2>&1`
  then
    [ -n "$MESSAGE" ] && $ZENITY --warning --text="$MESSAGE"
  else
      $ZENITY --error --text="$MESSAGE"
  fi
}

show_demo ()
{
  local FILE

  if FILE=`$ZENITY --file-selection --title="$WHICHTEXT"`
  then
    run_avatarsay "$FILE"
  fi
}

zenity_edit ()
{
  local FILE TMP
  
  FILE="$2"
  TMP="${FILE}.$$.tmp"
  
  [ -e "$TMP" ] && return
  
  # output may be on stdout or stderr :-(
  zenity --text-info --title="$FILE" --filename="$FILE" --editable 2>&1 >"$TMP"
  mv "$TMP" "$FILE"
}

edit_demo ()
{
  local FILE ENCODING
  
  ENCODING="UTF-8"
  
  if FILE=`$ZENITY --file-selection --save --title="$FILEEDIT"` \
     && [ -n "$FILE" ]
  then
    if [ ! -e "$FILE" ]
    then
      {
        echo "#!$AVATARSAY"
        echo
	echo "[encoding $ENCODING]"
        [ -n "$AVATARIMAGE" ] && echo "[avatarimage $AVATARIMAGE]"
        echo
        echo "# Text:"
        echo
      } > "$FILE"
      chmod a+x "$FILE"
    fi
    
    # $FILE must be the second parameter for zenity_edit
    $AVTEDITOR --encoding=$ENCODING "$FILE" && run_avatarsay "$FILE"
  fi
}

show_manpage ()
{
  local MANPAGE
  
  if MANPAGE=`$ZENITY --entry --text="$WHICHMANPAGE"`
  then
    (
    MANWIDTH=80
    GROFF_TYPESETTER=latin1
    export MANWIDTH GROFF_TYPESETTER

    # execute the command
    man -t $MANPAGE 2>&1 \
      | $AVATARSAY $MODE --raw --encoding=ISO-8859-1 -
    )
  fi
}

choose_avatar_image ()
{
  AVATARIMAGE=`$ZENITY --file-selection --title "$WHICHAVATARIMAGE"`
  
  if [ -n "$AVATARIMAGE" ]
  then
     export AVATARIMAGE 
  else
     unset AVATARIMAGE
     $ZENITY --info --text="$DEFAULTAVATARIMAGE"
  fi
}

choose_fullscreen ()
{
  if $ZENITY --question --text="$FULLSCREENMODE"
  then MODE="--fullscreen" 
  else MODE="--window" 
  fi
}

save_settings ()
{
  {
  echo "MODE=$MODE"
  echo "AVATARIMAGE=$AVATARIMAGE"
  } > $CONFIGFILE
}

#########################################################################
# main program

if [ -z "$DISPLAY" ]
then
  echo "$NOX" 1>&2
  exit 1
fi

# seacrch for zenity
ZENITY=`command -v zenity`

if [ -z "$ZENITY" ]
then
    echo "$NOZENITY" 1>&2
    exit 1
fi

# search for avatarsay
[ -x "./avatarsay" ] && AVATARSAY=`pwd`/avatarsay
[ -z "$AVATARSAY" ] && AVATARSAY=`command -v avatarsay`

if [ -z "$AVATARSAY" ]
then
    $ZENITY --error --text "$NOAVATARSAY"
    exit 1
fi

# search for gedit, use zenity as fallback-editor
AVTEDITOR=`command -v gedit`
[ -z "$AVTEDITOR" ] && AVTEDITOR=zenity_edit

# read configuration
[ -r $CONFIGFILE ] && . $CONFIGFILE

if [ -n "$AVATARIMAGE" ]
then
   export AVATARIMAGE 
else
   unset AVATARIMAGE
fi

# main menu
while true
do
  MENU=`$ZENITY --list --title=AKFAvatar --width 355 --height 370 \
       --column "$KEY" --column "$WHATTODO" \
     T "$RUNTERMINAL" \
     D "$SHOWDEMO" \
     E "$EDITDEMO" \
     M "$SHOWMANPAGE" \
     I "$CHANGEAVATARIMAGE" \
     F "$FULLSCREENORWINDOW" \
     S "$SAVESETTINGS" \
     H "$HELP" \
     W "$WEBSITE" \
     X "$EXIT"` \
     || exit 0

  case $MENU in
    T) run_avatarsay --terminal ;;
    D) show_demo ;;
    E) edit_demo ;;
    M) show_manpage ;;
    I) choose_avatar_image ;;
    F) choose_fullscreen ;;
    S) save_settings ;;
    H) show_help ;;
    W) gnome-open "$WWW" || firefox "$WWW" & ;;
    X) exit 0 ;;
  esac

done
