#!/bin/sh

#########################################################################
# GNOME frontend for avatarsay using zenity, yelp, gedit
# Copyright (c) 2007 Andreas K. Foerster <info@akfoerster.de>
#
# This file is part of AKFAvatar
#
# AKFAvatar is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AKFAvatar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, see <http://www.gnu.org/licenses/>.
#########################################################################

CONFIGFILE=~/.gnome-akfavatar

# default mode
MODE=--window

# comment that out if you don't want to have the window centered
SDL_VIDEO_CENTERED=1
export SDL_VIDEO_CENTERED

# may be overridden by language specific content
WWW="http://akfoerster.de/akfavatar/"

case "$LANG" in
  de*) WWW="http://akfoerster.de/akfavatar/index.de.html"
       HELPTEXT="info:akfavatar-de"
       WHICHTEXT="Welchen Text mit AKFAvatar anzeigen?"
       FILEEDIT="Weche Datei editieren"
       PRINTONLY="Dies ist nur für Befehle, die etwas über die"
       PRINTONLY="$PRINTONLY Standard-Ausgabe oder die"
       PRINTONLY="$PRINTONLY Standard-Fehlerausgabe ausgeben."
       PRINTONLY="$PRINTONLY Man kann es nicht für interaktive Programme"
       PRINTONLY="$PRINTONLY verwenden."
       WHICHCOMMAND="Die Ausgabe welchen Befehles mit AKFAvatar anzeigen?"
       WHICHMANPAGE="Welche Hilfeseite (Manpage) mit AKFAvatar anzeigen?"
       MANPAGEERROR="Fehler beim Anzeigen der Manpage"
       WHICHAVATARIMAGE="Welches Bild als Avatar verwenden?"
       WHICHAVATARIMAGE="$WHICHAVATARIMAGE (\"Abbruch\" für Vorgabe)"
       DEFAULTAVATARIMAGE="Verwende das Vorgabe-Bild als Avatar"
       FULLSCREENMODE="Das Programm im Vollbild-Modus laufen lassen?"
       NOX="muss vom X-Window-System aus gestartet werden"
       NOZENITY="Befehl \"zenity\" nicht gefunden"
       NOAVATARSAY="Befehl \"avatarsay\" nicht gefunden"
       KEY="Taste"
       WHATTODO="was machen"
       SHOWDEMO="ein Demo oder eine Text-Datei anzeigen"
       EDITDEMO="ein Demo erstellen oder bearbeiten"
       SHOWMANPAGE="eine Hilfeseite (Manpage) anzeigen"
       SHOWCOMMAND="zeige die Ausgabe eines Befehls"
       CHANGEAVATARIMAGE="ändere das Avatar-Bild"
       FULLSCREENORWINDOW="Vollbild- oder Fenster-Modus"
       SAVESETTINGS="speichere Einstellungen"
       HELP="Hilfe für AKFAvatar"
       WEBSITE="Website"
       EXIT="beenden";;

  *)   WWW="http://akfoerster.de/akfavatar/index.en.html"
       HELPTEXT="info:akfavatar-en"
       WHICHTEXT="Which text to show with AKFAvatar?"
       FILEEDIT="file to edit"
       PRINTONLY="This is only for commands which only print text to "
       PRINTONLY="$PRINTONLY standard output or standard error."
       PRINTONLY="$PRINTONLY You can not use interactive commands with this."
       WHICHCOMMAND="The output of which command to show with AKFAvatar?"
       WHICHMANPAGE="Which manpage to show with AKFAvatar?"
       MANPAGEERROR="error showing manpage"
       WHICHAVATARIMAGE="Which image to use as avatar? (cancel for default)"
       DEFAULTAVATARIMAGE="Using the default avatar image"
       FULLSCREENMODE="Run the program in fullscreen mode?"
       NOX="must be started from the X-Window-System"
       NOZENITY="Command \"zenity\" not found"
       NOAVATARSAY="Command \"avatarsay\" not found"
       KEY="key"
       WHATTODO="what to do"
       SHOWDEMO="show a demo or textfile"
       EDITDEMO="create or edit a demo"
       SHOWMANPAGE="show a manpage"
       SHOWCOMMAND="show the output of a command"
       CHANGEAVATARIMAGE="change avatar image"
       FULLSCREENORWINDOW="fullscreen or window mode"
       SAVESETTINGS="save settings"
       HELP="help for AKFAvatar"
       WEBSITE="Website"
       EXIT="Exit";;
esac

#########################################################################
# functions

run_avatarsay ()
{
  local MESSAGE

  if [ "$1" = "-" -o -r "$1" ]
  then
    if MESSAGE=`$AVATARSAY $MODE "$1" 2>&1`
    then
      [ -n "$MESSAGE" ] && $ZENITY --warning --text="$MESSAGE"
    else
      $ZENITY --error --text="$MESSAGE"
    fi
  fi
}

show_demo ()
{
  local FILE

  if FILE=`$ZENITY --file-selection --title="$WHICHTEXT"`
  then
    run_avatarsay "$FILE"
  fi
}

edit_demo ()
{
  local FILE ENCODING
  
  ENCODING="UTF-8"
  
  if FILE=`$ZENITY --file-selection --save --title="$FILEEDIT"` \
     && [ -n "$FILE" ]
  then
    if [ ! -e "$FILE" ]
    then
      {
        echo "#!$AVATARSAY"
        echo
	echo ".encoding $ENCODING"
        [ -n "$AVATARIMAGE" ] && echo ".avatarimage $AVATARIMAGE"
        echo
        echo "# Text:"
        echo
      } > "$FILE"
      chmod a+x "$FILE"
    fi
    
    gedit --encoding=$ENCODING "$FILE" && run_avatarsay "$FILE"
  fi
}

show_command ()
{
  local COMMAND
  
  $ZENITY --warning \
  --text="$PRINTONLY" || return

  COMMAND=`$ZENITY --entry --text="$WHICHCOMMAND"` \
  && [ -n "$COMMAND" ] \
  && type $COMMAND > /dev/null 2>&1 \
  && $COMMAND 2>&1 | run_avatarsay -
}

show_manpage ()
{
  local MANPAGE
  
  if MANPAGE=`$ZENITY --entry --text="$WHICHMANPAGE"`
  then
    (
    TERM=dumb
    PAGER="$AVATARSAY $MODE --raw -"
    MANWIDTH=80
    export PAGER MANWIDTH TERM

    # execute the command
    man $MANPAGE 2>/dev/null \
      || $ZENITY --error --text="$MANPAGEERROR"
    )
  fi
}

choose_avatar_image ()
{
  AVATARIMAGE=`$ZENITY --file-selection --title "$WHICHAVATARIMAGE"`
  
  if [ -n "$AVATARIMAGE" ]
  then
     export AVATARIMAGE 
  else
     unset AVATARIMAGE
     $ZENITY --info --text="$DEFAULTAVATARIMAGE"
  fi
}

choose_fullscreen ()
{
  if $ZENITY --question --text="$FULLSCREENMODE"
  then MODE="--fullscreen" 
  else MODE="--window" 
  fi
}

save_settings ()
{
  {
  echo "MODE=$MODE"
  echo "AVATARIMAGE=$AVATARIMAGE"
  } > $CONFIGFILE
}

#########################################################################
# main program

if [ -z "$DISPLAY" ]
then
  echo "$NOX" 1>&2
  exit 1
fi

# seacrch for zenity
ZENITY=`command -v zenity`

if [ -z "$ZENITY" ]
then
    echo "$NOZENITY" 1>&2
    exit 1
fi

# search for avatarsay
AVATARSAY=`command -v avatarsay`
[ -z "$AVATARSAY" -a -x "./avatarsay" ] && AVATARSAY=`pwd`/avatarsay

if [ -z "$AVATARSAY" ]
then
    $ZENITY --error --text "$NOAVATARSAY"
    exit 1
fi

# read configuration
[ -r $CONFIGFILE ] && . $CONFIGFILE

if [ -n "$AVATARIMAGE" ]
then
   export AVATARIMAGE 
else
   unset AVATARIMAGE
fi

# main menu
while true
do
  MENU=`$ZENITY --list --title=AKFAvatar --width 355 --height 370 \
       --column "$KEY" --column "$WHATTODO" \
     D "$SHOWDEMO" \
     E "$EDITDEMO" \
     M "$SHOWMANPAGE" \
     C "$SHOWCOMMAND" \
     I "$CHANGEAVATARIMAGE" \
     F "$FULLSCREENORWINDOW" \
     S "$SAVESETTINGS" \
     H "$HELP" \
     W "$WEBSITE" \
     X "$EXIT"` \
     || exit 0

  case $MENU in
    D) show_demo ;;
    E) edit_demo ;;
    M) show_manpage ;;
    C) show_command ;;
    I) choose_avatar_image ;;
    F) choose_fullscreen ;;
    S) save_settings ;;
    H) yelp "$HELPTEXT" & ;;
    W) gnome-open "$WWW" ;;
    X) exit 0 ;;
  esac

done
