#!/bin/sh
# this file is in the Public Domain -- AKFoerster

if [ $# -eq 0 -o "$1" = "--help" -o "$1" = "-h" ]
then
  echo "usage: ./lrun program"
  echo "lrun runs programs using libraries in lrun's directory"
  exit 0
fi

localdir=$(dirname $0)
test "$localdir" = "." && localdir=$(pwd)

PATH=$PATH:$localdir:.
INFOPATH=$INFOPATH:$localdir:$localdir/doc

if [ -z "$LD_LIBRARY_PATH" ]
then
  LD_LIBRARY_PATH="$localdir"
else
  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$localdir"
fi

export PATH INFOPATH LD_LIBRARY_PATH

exec "$@"
