#!/bin/sh
# this file is in the Public Domain -- AKFoerster

localdir=$(dirname "$0")
test "$localdir" = "." && localdir=$(pwd)

PATH="${PATH:+$PATH:}$localdir:."
LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$localdir"

export PATH LD_LIBRARY_PATH

exec ./lua-akfavatar-bin "$@"
