.\" Process this file with
.\" groff -man -Tutf8 lua-akfavatar.1
.\"
.TH "lua-akfavatar" 1 2012-04-09 AKFAvatar
.
.SH NAME
lua-akfavatar \- Lua interpreter for the AKFAvatar user interface
.
.SH SYNOPSIS
.BI "local " avt " = lua-akfavatar [" options "] [" " script " "[" args "] ]"
.
.SH DESCRIPTION
The program Lua-AKFAvatar is the Lua interpreter for the AKFAvatar
user interface.
It loads and executes Lua scripts in source form (not bytecode).
Either Lua scripts can be loaded or ".avt" demo files.
If no
.I script
is given, it starts with a file-selector.  The file-selector starts in
the current working directory, or in the directory given with the option
.IR --dir=directory .
.PP
The given
.I args
are available to
.I script
as strings in a global table named
.BR arg .
The
.I script
itself is in
.BR arg[0] ,
the first argument is
.B arg[1]
and so on.
.PP
You have to use the command
.BI "local " avt " = require """ lua-akfavatar """"
to get access to the AKFAvatar specific functions.
.PP
With the file-selector you can also see documentation files
with the file extension
.RI """" .about """."
These can be simple text files encoded in UTF-8 or plain ASCII.
They can use the "overstriking" technique for bold or underlined text.
You can for example use the text-setting system "groff" to generate
such files.
.
.SH OPTIONS
.IP "-h | --help"
print a short help-message
.IP "-v | --version"
print version information
.TP
.RI "-l " name
call
.BI require(' name ')
before executing the script.
Typically used to load libraries.
.TP
.RI --dir= dir
Start in that directory
.
.SH ENVIRONMENT
.TP
LUA_PATH_5_2
.TQ
LUA_PATH
searchpath for Lua modules.
Templates are separated with semicolons.
A question mark
.RB ( ? )
is replaced with the module name.
A dot in the module name is replaced with the directory separator.
Two semicolons
.B (;;)
add the default path.
.TP
LUA_CPATH_5_2
.TQ
LUA_CPATH
searchpath for C modules.  Syntax like in
.IR LUA_PATH .
.TP
AVTDATAPATH
searchpath for data files (images, audio, texts...).
It gets stored in the variable
.I avt.datapath
and can be used with the function
.IR avt.search(filename) .
The directories are separated with semicolons.
Unlike the former paths there are no templates with question marks.
.
.SH EXAMPLE
.nf
local avt = require "lua-akfavatar"
avt.encoding("UTF-8")
avt.title("my first program")
avt.start()
avt.say("Hello there!\\n")
local user = avt.ask("What's your name? ")
avt.say("Hello, ", user, ". Nice to meet you!\\n")
avt.wait_button()
.fi
.
.SH AUTHORS
.IP "AKFAvatar, Lua-AKFAvatar"
Andreas K. Foerster
.IP "Lua"
R. Ierusalimschy, L. H. de Figueiredo, and W. Celes
.
.SH HOMEPAGE
http://akfavatar.nongnu.org/
.
.SH "SEE ALSO"
.BR lua (1)
.BR lua-akfavatar-ref (3)
.PP
http://akfavatar.nongnu.org/manual/
.br
http://www.lua.org/manual/5.2/
